### ISSUE TITLE
 import and export GInteraction object

### ISSUE THREAD

**Issue by crazyhottommy** [LTLA/InteractionSet#1]
Hi,
Thanks for this useful package.

How to easily import a bedpe file to GInteraction object and save the object to a bedpe file on disk?
now, I am doing

```R
library(rtracklayer)
library(InteractionSet)

encode_bedpe<- rtracklayer::import("my.bedpe", format = "bedpe")


gi<- GInteractions(first(encode_bedpe), second(encode_bedpe), mode= "strict")

# how to save gi to bedpe file?
```
Thanks!
Tommy

**Comment by LTLA** [comment]
We have a `makeGInteractionsFromGRangesPairs` to go from `Pairs` object to a `GInteractions`.

You can go the other way using the `pairs` function, from which I presume you should be able to save to a BEDPE format using `rtracklayer::export`. I've never tried this, though.

**Comment by crazyhottommy** [comment]
It works. Thank you!
Tommy
