### ISSUE TITLE
Last commit not pushed to Bioc 3.17

### ISSUE THREAD

**Issue by js2264** [LTLA/InteractionSet#10]
Hi @LTLA, 

`inflate()` used to be working well for me with version `1.27.1`, but it stopped working when I updated it to `1.28.0`. Downgrading to github `1.27.1` works but is not ideal. 

I noticed that your commit https://github.com/LTLA/InteractionSet/commit/e908ba98e31a64e0bfca7f8be6ba753c3cfaec95 in this repo had not been pushed to Bioconductor 3.17. It was included in Bioc 3.16, but was somehow not included in the new release 3.17. Is there any reason for that? Is there any way you could push this commit to `1.28.0` too? 

Thanks, 
Jacques

**Comment by LTLA** [comment]
Oops. This should be fixed soon in 1.28.1 and 1.29.1.
